Complete Your First Project in R
Exploring Customer Data

```{r}
#run first
library(xlsx)
library(dplyr)
sales <- read.xlsx("/Users/megansilvey/Documents/LinkedIn Learning/R Project Course/Red30 Tech Sales.xlsx",1)
customers <- read.xlsx("/Users/megansilvey/Documents/LinkedIn Learning/R Project Course/Red30 Tech Customers.xlsx",1)
```

```{r}
#get customer type by total number of orders
table(sales$CustomerType)
prop.table(table(sales$CustomerType))

```


```{r}
#average sales and quantity by customer type
sales %>% group_by(CustomerType)  %>%
                    summarise(mean_sales = mean(Order.Total), 
                              mean_quantity = mean(Quantity), 
                              .groups = 'drop')
```


```{r}
#total sales and quantity by customer type
sales %>% group_by(CustomerType)  %>%
                    summarise(total_sales = sum(Order.Total), 
                              total_quantity = sum(Quantity), 
                              .groups = 'drop')
```

```{r}
#get top customer states by total number of orders
sales %>% count(CustState, sort = TRUE)
```

```{r}
#get top customer states by total number of customers
customers %>% count(CustState, sort = TRUE)
```

```{r}
#get top customer cities by total number of customers
customers %>% count(CustCity, sort = TRUE)
```

```{r}
#get top customer states by total number of customers
customers %>% count(CustZip, sort = TRUE)
```

```{r}
#review product categories sold by customer type
table(sales$CustomerType, sales$ProdCategory)
```

```{r}
#review product categories sold by customer state
table(sales$CustState, sales$ProdCategory)
```

