Complete Your First Project in R
Classification Analysis

```{r}
#run first
library(openxlsx)
sales <- read.xlsx("Red30 Tech Sales.xlsx",1,detectDates = TRUE)
sales$OrderMonth <- format(sales$OrderDate,"%B")
sales$OrderYear <- format(sales$OrderDate,"%Y")
sales$Payment.Status <- factor(sales$Payment.Status)
summary(sales)
```

```{r}
#run first
sales_subset <- subset(sales, select = c(Employee.Job.Title , Sales.Region , OrderMonth
                     ,OrderYear , OrderType , CustomerType , ProdCategory
                     , Quantity , Price , Discount , Order.Total , Payment.Plan, Payment.Status))

set.seed(42)
bound <- floor((nrow(sales_subset)/4)*3)         #define % of training and test set

df <- sales_subset[sample(nrow(sales_subset)), ]           #sample rows 
train <- df[1:bound, ]              #get training set
test <- df[(bound+1):nrow(df), ]    #get test set
summary(train)
summary(test)
```

```{r}
#install package if needed
install.packages("e1071")
```


```{r}
#load package
library(e1071)
```


```{r}
#create SVM model
classifier <- svm(formula = Payment.Status ~ ., 
                 data = train, 
                 type = 'C-classification', 
                 kernel = 'linear') 
```

```{r}
#get summary of classifier
summary(classifier)
```

```{r}
#predict on model
test$test_pred_svm <- predict(classifier,test)
test 
```



