Complete Your First Project in R
Cluster Analysis

```{r}
#run first
library(openxlsx)
library(ggplot2)
sales <- read.xlsx("Red30 Tech Sales.xlsx",1,detectDates = TRUE)
sales$OrderMonth <- format(sales$OrderDate,"%B")
sales$OrderYear <- format(sales$OrderDate,"%Y")
summary(sales)
```

```{r}
#install packages if needed
install.packages("lattice")
install.packages("caret")
```


```{r}
#import packages
library(lattice)
library(caret)
```

```{r}
#get subset of data
sales_subset <- subset(sales, select = c(Employee.Job.Title , Sales.Region , OrderMonth,
                     OrderYear , OrderType , CustomerType , CustState, ProdCategory, 
                     Quantity , Price , Discount , Order.Total , Payment.Plan, Payment.Status))
```

```{r}
#remove null values
sales_subset <- na.omit(sales_subset)
summary(sales_subset)
```


```{r}
#encode dummy variables
dummy_var <- dummyVars(" ~ .", data = sales_subset)
trsf <- data.frame(predict(dummy_var, newdata = sales_subset))
trsf
```


```{r}
#normalize data
trsf.pre <- preProcess(trsf, method="range")
scaled_data <- predict(trsf.pre, trsf)
summary(scaled_data)
```

