Complete Your First Project in R
Cluster Analysis

```{r}
#run first
library(ggplot2)
library(lattice)
library(caret)
library(cluster)
library(openxlsx)
sales <- read.xlsx("Red30 Tech Sales.xlsx",1,detectDates = TRUE)
sales$OrderMonth <- format(sales$OrderDate,"%B")
sales$OrderYear <- format(sales$OrderDate,"%Y")
summary(sales)
```



```{r}
#run first
set.seed(42)
sales_subset <- subset(sales, select = c(Employee.Job.Title , Sales.Region , OrderMonth,
                     OrderYear , OrderType , CustomerType , CustState, ProdCategory,
                     Quantity , Price , Discount , Order.Total , Payment.Plan, Payment.Status))

sales_subset <- na.omit(sales_subset)
dmy <- dummyVars(" ~ .", data = sales_subset)
trsf <- data.frame(predict(dmy, newdata = sales_subset))
trsf.pre <- preProcess(trsf, method="range")
scaled_data <- predict(trsf.pre, trsf)
```


```{r}
#Create distance matrix
distance_mat <- dist(scaled_data, method = 'euclidean')
```

```{r}
#Fit hierarchical clustering model
Hierar_cl <- hclust(distance_mat, method = "average")
Hierar_cl
```

```{r fig.width=12, fig.height=10}
#Plot dendrogram
plot(Hierar_cl)
abline(h=4, col = "red")
```


```{r}
# Cut tree into clusters
sub_grp <- cutree(Hierar_cl, k = 2)
table(sub_grp)
```


```{r fig.width=12, fig.height=10}
#Plot dendrogram
plot(Hierar_cl)
rect.hclust(Hierar_cl , k = 2)
```


```{r fig.width=10, fig.height=7}
#Determine silhouette score
plot(silhouette(cutree(Hierar_cl, k=2) ,distance_mat, border=NA)) 
```

