Complete Your First Project in R
Cluster Analysis

```{r}
#run first
library(openxlsx)
library(lattice)
library(caret)
library(dplyr)
library(ggplot2)
library(cluster)
library(factoextra)
```


```{r}
#run first
sales <- read.xlsx("Red30 Tech Sales.xlsx",1,detectDates = TRUE)
sales$OrderMonth <- format(sales$OrderDate,"%B")
sales$OrderYear <- format(sales$OrderDate,"%Y")
summary(sales)
```


```{r}
#run first
set.seed(42)
sales_subset <- subset(sales, select = c(Employee.Job.Title , Sales.Region , OrderMonth,
                     OrderYear , OrderType , CustomerType , CustState, ProdCategory,
                     Quantity , Price , Discount , Order.Total , Payment.Plan, Payment.Status))
 
sales_subset <- na.omit(sales_subset)
dmy <- dummyVars(" ~ .", data = sales_subset)
trsf <- data.frame(predict(dmy, newdata = sales_subset))
trsf.pre <- preProcess(trsf, method="range")
scaled_data <- predict(trsf.pre, trsf)
```


```{r}
#run first
km <- kmeans(scaled_data, centers = 2, nstart = 25)
km
```


```{r}
#Add cluster column to final dataset
final_data <- cbind(sales, cluster = km$cluster)
final_data
```


```{r}
#summarize data
final_data %>% group_by(cluster)  %>%
                    summarise(across(everything(), list(mean)))
```


```{r}
#evaluate categorical variables
table(final_data$cluster, final_data$Payment.Status)
```


```{r}
#add column to scaled dataset
final_scaled_data <- cbind(scaled_data, cluster = km$cluster)
final_scaled_data
```


```{r}
#summarize data all numerically
final_scaled_data %>% group_by(cluster)  %>%
                    summarise(across(everything(), list(mean)))
```