Complete Your First Project in R
Cluster Analysis

```{r}
#run first
library(ggplot2)
library(lattice)
library(caret)
library(factoextra)
library(cluster)
library(openxlsx)
sales <- read.xlsx("Red30 Tech Sales.xlsx",1,detectDates = TRUE)
sales$OrderMonth <- format(sales$OrderDate,"%B")
sales$OrderYear <- format(sales$OrderDate,"%Y")
summary(sales)
```


```{r}
#run first, removed product name
set.seed(42)
sales_subset <- subset(sales, select = c(Employee.Job.Title , Sales.Region , OrderMonth,
                     OrderYear , OrderType , CustomerType , CustState, ProdCategory,
                     Quantity , Price , Discount , Order.Total , Payment.Plan, Payment.Status))
 
sales_subset <- na.omit(sales_subset)
dmy <- dummyVars(" ~ .", data = sales_subset)
trsf <- data.frame(predict(dmy, newdata = sales_subset))
trsf.pre <- preProcess(trsf, method="range")
scaled_data <- predict(trsf.pre, trsf)
```


```{r}
#install packages if needed
install.packages("ClusterR")
```

```{r}
#import packages

```

```{r}
#Find optimal number of clusters based on BIC

```


```{r}
#Find optimal number of clusters based on AIC

```

```{r}
#run GMM model for selected number of clusters

```

```{r}
# predict clusters

```


```{r}
#Transform the gmm_cluster variable into a list

```


```{r}
#Add cluster column to final dataset

```

```{r}
#Look at cluster sizes

```



```{r}
#Determine silhouette score

```

